// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: spark_ssp.proto

package spark_ssp

import (
	context "context"
	spark "github.com/lightsparkdev/spark/proto/spark"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SparkSspService_PrepareTreeAddress_FullMethodName                  = "/spark_ssp.SparkSspService/prepare_tree_address"
	SparkSspService_CreateTree_FullMethodName                          = "/spark_ssp.SparkSspService/create_tree"
	SparkSspService_CounterLeafSwapV3_FullMethodName                   = "/spark_ssp.SparkSspService/counter_leaf_swap_v3"
	SparkSspService_InitiateUtxoSwap_FullMethodName                    = "/spark_ssp.SparkSspService/initiate_utxo_swap"
	SparkSspService_ReserveInstantStaticDepositUtxoSwap_FullMethodName = "/spark_ssp.SparkSspService/reserve_instant_static_deposit_utxo_swap"
	SparkSspService_ClaimInstantStaticDepositUtxoSwap_FullMethodName   = "/spark_ssp.SparkSspService/claim_instant_static_deposit_utxo_swap"
)

// SparkSspServiceClient is the client API for SparkSspService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The calls a Spark service provider makes that a wallet never does. They are
// served here rather than on SparkService so that spark.proto stays the file
// upstream defines, and this one carries the whole SSP surface.
type SparkSspServiceClient interface {
	// Prepares the addresses of a deposit tree's nodes, then builds and signs the
	// tree itself. An SSP turns one on-chain deposit into the denominated leaves
	// its pool hands out, which is what these two do.
	PrepareTreeAddress(ctx context.Context, in *spark.PrepareTreeAddressRequest, opts ...grpc.CallOption) (*spark.PrepareTreeAddressResponse, error)
	CreateTree(ctx context.Context, in *spark.CreateTreeRequest, opts ...grpc.CallOption) (*spark.CreateTreeResponse, error)
	// Answers a user's swap with the counter transfer. The operators atomically
	// commit both transfers' sender key tweaks, so neither side can take leaves
	// without giving leaves in return.
	CounterLeafSwapV3(ctx context.Context, in *spark.CounterLeafSwapRequest, opts ...grpc.CallOption) (*spark.CounterLeafSwapResponse, error)
	// Claims a static deposit as a fixed-amount UTXO swap: the SSP hands the user a
	// Spark transfer in exchange for the on-chain UTXO, and the SE co-signs the SSP's
	// spend transaction. Errors if the UTXO has already been claimed.
	InitiateUtxoSwap(ctx context.Context, in *spark.InitiateUtxoSwapRequest, opts ...grpc.CallOption) (*spark.InitiateUtxoSwapResponse, error)
	// The same claim in two phases, so the user is credited before their deposit
	// confirms: reserve credits them against a UTXO that may be unconfirmed, and
	// claim completes the swap once it has confirmed.
	ReserveInstantStaticDepositUtxoSwap(ctx context.Context, in *ReserveInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ReserveInstantStaticDepositUtxoSwapResponse, error)
	ClaimInstantStaticDepositUtxoSwap(ctx context.Context, in *ClaimInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ClaimInstantStaticDepositUtxoSwapResponse, error)
}

type sparkSspServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSparkSspServiceClient(cc grpc.ClientConnInterface) SparkSspServiceClient {
	return &sparkSspServiceClient{cc}
}

func (c *sparkSspServiceClient) PrepareTreeAddress(ctx context.Context, in *spark.PrepareTreeAddressRequest, opts ...grpc.CallOption) (*spark.PrepareTreeAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.PrepareTreeAddressResponse)
	err := c.cc.Invoke(ctx, SparkSspService_PrepareTreeAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspServiceClient) CreateTree(ctx context.Context, in *spark.CreateTreeRequest, opts ...grpc.CallOption) (*spark.CreateTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.CreateTreeResponse)
	err := c.cc.Invoke(ctx, SparkSspService_CreateTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspServiceClient) CounterLeafSwapV3(ctx context.Context, in *spark.CounterLeafSwapRequest, opts ...grpc.CallOption) (*spark.CounterLeafSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.CounterLeafSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspService_CounterLeafSwapV3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspServiceClient) InitiateUtxoSwap(ctx context.Context, in *spark.InitiateUtxoSwapRequest, opts ...grpc.CallOption) (*spark.InitiateUtxoSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.InitiateUtxoSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspService_InitiateUtxoSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspServiceClient) ReserveInstantStaticDepositUtxoSwap(ctx context.Context, in *ReserveInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ReserveInstantStaticDepositUtxoSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveInstantStaticDepositUtxoSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspService_ReserveInstantStaticDepositUtxoSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspServiceClient) ClaimInstantStaticDepositUtxoSwap(ctx context.Context, in *ClaimInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ClaimInstantStaticDepositUtxoSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimInstantStaticDepositUtxoSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspService_ClaimInstantStaticDepositUtxoSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SparkSspServiceServer is the server API for SparkSspService service.
// All implementations must embed UnimplementedSparkSspServiceServer
// for forward compatibility.
//
// The calls a Spark service provider makes that a wallet never does. They are
// served here rather than on SparkService so that spark.proto stays the file
// upstream defines, and this one carries the whole SSP surface.
type SparkSspServiceServer interface {
	// Prepares the addresses of a deposit tree's nodes, then builds and signs the
	// tree itself. An SSP turns one on-chain deposit into the denominated leaves
	// its pool hands out, which is what these two do.
	PrepareTreeAddress(context.Context, *spark.PrepareTreeAddressRequest) (*spark.PrepareTreeAddressResponse, error)
	CreateTree(context.Context, *spark.CreateTreeRequest) (*spark.CreateTreeResponse, error)
	// Answers a user's swap with the counter transfer. The operators atomically
	// commit both transfers' sender key tweaks, so neither side can take leaves
	// without giving leaves in return.
	CounterLeafSwapV3(context.Context, *spark.CounterLeafSwapRequest) (*spark.CounterLeafSwapResponse, error)
	// Claims a static deposit as a fixed-amount UTXO swap: the SSP hands the user a
	// Spark transfer in exchange for the on-chain UTXO, and the SE co-signs the SSP's
	// spend transaction. Errors if the UTXO has already been claimed.
	InitiateUtxoSwap(context.Context, *spark.InitiateUtxoSwapRequest) (*spark.InitiateUtxoSwapResponse, error)
	// The same claim in two phases, so the user is credited before their deposit
	// confirms: reserve credits them against a UTXO that may be unconfirmed, and
	// claim completes the swap once it has confirmed.
	ReserveInstantStaticDepositUtxoSwap(context.Context, *ReserveInstantStaticDepositUtxoSwapRequest) (*ReserveInstantStaticDepositUtxoSwapResponse, error)
	ClaimInstantStaticDepositUtxoSwap(context.Context, *ClaimInstantStaticDepositUtxoSwapRequest) (*ClaimInstantStaticDepositUtxoSwapResponse, error)
	mustEmbedUnimplementedSparkSspServiceServer()
}

// UnimplementedSparkSspServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSparkSspServiceServer struct{}

func (UnimplementedSparkSspServiceServer) PrepareTreeAddress(context.Context, *spark.PrepareTreeAddressRequest) (*spark.PrepareTreeAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareTreeAddress not implemented")
}
func (UnimplementedSparkSspServiceServer) CreateTree(context.Context, *spark.CreateTreeRequest) (*spark.CreateTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTree not implemented")
}
func (UnimplementedSparkSspServiceServer) CounterLeafSwapV3(context.Context, *spark.CounterLeafSwapRequest) (*spark.CounterLeafSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CounterLeafSwapV3 not implemented")
}
func (UnimplementedSparkSspServiceServer) InitiateUtxoSwap(context.Context, *spark.InitiateUtxoSwapRequest) (*spark.InitiateUtxoSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateUtxoSwap not implemented")
}
func (UnimplementedSparkSspServiceServer) ReserveInstantStaticDepositUtxoSwap(context.Context, *ReserveInstantStaticDepositUtxoSwapRequest) (*ReserveInstantStaticDepositUtxoSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveInstantStaticDepositUtxoSwap not implemented")
}
func (UnimplementedSparkSspServiceServer) ClaimInstantStaticDepositUtxoSwap(context.Context, *ClaimInstantStaticDepositUtxoSwapRequest) (*ClaimInstantStaticDepositUtxoSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimInstantStaticDepositUtxoSwap not implemented")
}
func (UnimplementedSparkSspServiceServer) mustEmbedUnimplementedSparkSspServiceServer() {}
func (UnimplementedSparkSspServiceServer) testEmbeddedByValue()                         {}

// UnsafeSparkSspServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SparkSspServiceServer will
// result in compilation errors.
type UnsafeSparkSspServiceServer interface {
	mustEmbedUnimplementedSparkSspServiceServer()
}

func RegisterSparkSspServiceServer(s grpc.ServiceRegistrar, srv SparkSspServiceServer) {
	// If the following call panics, it indicates UnimplementedSparkSspServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SparkSspService_ServiceDesc, srv)
}

func _SparkSspService_PrepareTreeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.PrepareTreeAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspServiceServer).PrepareTreeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspService_PrepareTreeAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspServiceServer).PrepareTreeAddress(ctx, req.(*spark.PrepareTreeAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspService_CreateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.CreateTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspServiceServer).CreateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspService_CreateTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspServiceServer).CreateTree(ctx, req.(*spark.CreateTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspService_CounterLeafSwapV3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.CounterLeafSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspServiceServer).CounterLeafSwapV3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspService_CounterLeafSwapV3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspServiceServer).CounterLeafSwapV3(ctx, req.(*spark.CounterLeafSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspService_InitiateUtxoSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.InitiateUtxoSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspServiceServer).InitiateUtxoSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspService_InitiateUtxoSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspServiceServer).InitiateUtxoSwap(ctx, req.(*spark.InitiateUtxoSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspService_ReserveInstantStaticDepositUtxoSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveInstantStaticDepositUtxoSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspServiceServer).ReserveInstantStaticDepositUtxoSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspService_ReserveInstantStaticDepositUtxoSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspServiceServer).ReserveInstantStaticDepositUtxoSwap(ctx, req.(*ReserveInstantStaticDepositUtxoSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspService_ClaimInstantStaticDepositUtxoSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimInstantStaticDepositUtxoSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspServiceServer).ClaimInstantStaticDepositUtxoSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspService_ClaimInstantStaticDepositUtxoSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspServiceServer).ClaimInstantStaticDepositUtxoSwap(ctx, req.(*ClaimInstantStaticDepositUtxoSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SparkSspService_ServiceDesc is the grpc.ServiceDesc for SparkSspService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SparkSspService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spark_ssp.SparkSspService",
	HandlerType: (*SparkSspServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "prepare_tree_address",
			Handler:    _SparkSspService_PrepareTreeAddress_Handler,
		},
		{
			MethodName: "create_tree",
			Handler:    _SparkSspService_CreateTree_Handler,
		},
		{
			MethodName: "counter_leaf_swap_v3",
			Handler:    _SparkSspService_CounterLeafSwapV3_Handler,
		},
		{
			MethodName: "initiate_utxo_swap",
			Handler:    _SparkSspService_InitiateUtxoSwap_Handler,
		},
		{
			MethodName: "reserve_instant_static_deposit_utxo_swap",
			Handler:    _SparkSspService_ReserveInstantStaticDepositUtxoSwap_Handler,
		},
		{
			MethodName: "claim_instant_static_deposit_utxo_swap",
			Handler:    _SparkSspService_ClaimInstantStaticDepositUtxoSwap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spark_ssp.proto",
}
