// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: spark_ssp.proto

package spark_ssp

import (
	spark "github.com/lightsparkdev/spark/proto/spark"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Phase one of the instant (0-conf) static-deposit swap: the SSP asks the SE to credit the
// user a Spark transfer against a deposit UTXO that may still be unconfirmed. The reservation
// stays open until the claim phase sweeps the UTXO once it confirms.
type ReserveInstantStaticDepositUtxoSwapRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OnChainUtxo *spark.UTXO            `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	// SSP signature over the message consenting to credit a specific amount for a specific UTXO.
	SspSignature []byte `protobuf:"bytes,2,opt,name=ssp_signature,json=sspSignature,proto3" json:"ssp_signature,omitempty"`
	// User signature over the message consenting to exchange the UTXO for the SSP's transfer.
	UserSignature []byte `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	// Transfer package crediting the user, sent from the SSP.
	Transfer *spark.StartTransferRequest `protobuf:"bytes,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Static deposit address the UTXO was paid to.
	DestinationAddress string `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	// UTXO output value in satoshis.
	ValueSats int64 `protobuf:"varint,6,opt,name=value_sats,json=valueSats,proto3" json:"value_sats,omitempty"`
	// Primary credit amount in satoshis.
	CreditAmountSats int64 `protobuf:"varint,7,opt,name=credit_amount_sats,json=creditAmountSats,proto3" json:"credit_amount_sats,omitempty"`
	// Optional secondary credit amount in satoshis (claimed with a secondary transfer).
	SecondaryCreditAmountSats int64 `protobuf:"varint,8,opt,name=secondary_credit_amount_sats,json=secondaryCreditAmountSats,proto3" json:"secondary_credit_amount_sats,omitempty"`
	// Requested secondary transfer id, required iff secondary_credit_amount_sats is set.
	RequestedSecondaryTransferId string `protobuf:"bytes,10,opt,name=requested_secondary_transfer_id,json=requestedSecondaryTransferId,proto3" json:"requested_secondary_transfer_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) Reset() {
	*x = ReserveInstantStaticDepositUtxoSwapRequest{}
	mi := &file_spark_ssp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstantStaticDepositUtxoSwapRequest) ProtoMessage() {}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstantStaticDepositUtxoSwapRequest.ProtoReflect.Descriptor instead.
func (*ReserveInstantStaticDepositUtxoSwapRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetSspSignature() []byte {
	if x != nil {
		return x.SspSignature
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetUserSignature() []byte {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetValueSats() int64 {
	if x != nil {
		return x.ValueSats
	}
	return 0
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetCreditAmountSats() int64 {
	if x != nil {
		return x.CreditAmountSats
	}
	return 0
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetSecondaryCreditAmountSats() int64 {
	if x != nil {
		return x.SecondaryCreditAmountSats
	}
	return 0
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetRequestedSecondaryTransferId() string {
	if x != nil {
		return x.RequestedSecondaryTransferId
	}
	return ""
}

type ReserveInstantStaticDepositUtxoSwapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary transfer crediting the user, sent at reserve time.
	Transfer *spark.Transfer `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Reservation handle the claim phase uses to locate this swap.
	UtxoSwapId    string `protobuf:"bytes,2,opt,name=utxo_swap_id,json=utxoSwapId,proto3" json:"utxo_swap_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) Reset() {
	*x = ReserveInstantStaticDepositUtxoSwapResponse{}
	mi := &file_spark_ssp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstantStaticDepositUtxoSwapResponse) ProtoMessage() {}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstantStaticDepositUtxoSwapResponse.ProtoReflect.Descriptor instead.
func (*ReserveInstantStaticDepositUtxoSwapResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) GetUtxoSwapId() string {
	if x != nil {
		return x.UtxoSwapId
	}
	return ""
}

// Phase two of the instant static-deposit swap: the reserved UTXO has confirmed, so the SE
// co-signs the SSP's spend transaction and sends any secondary transfer, then completes the swap.
type ClaimInstantStaticDepositUtxoSwapRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OnChainUtxo *spark.UTXO            `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	// Reservation handle returned by the reserve phase.
	UtxoSwapId string `protobuf:"bytes,2,opt,name=utxo_swap_id,json=utxoSwapId,proto3" json:"utxo_swap_id,omitempty"`
	// Optional secondary transfer package, present iff the reservation has a secondary credit.
	Transfer *spark.StartTransferRequest `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Transaction the SSP built spending the UTXO to an address it owns.
	SpendTxSigningJob *spark.SigningJob `protobuf:"bytes,4,opt,name=spend_tx_signing_job,json=spendTxSigningJob,proto3" json:"spend_tx_signing_job,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) Reset() {
	*x = ClaimInstantStaticDepositUtxoSwapRequest{}
	mi := &file_spark_ssp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimInstantStaticDepositUtxoSwapRequest) ProtoMessage() {}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimInstantStaticDepositUtxoSwapRequest.ProtoReflect.Descriptor instead.
func (*ClaimInstantStaticDepositUtxoSwapRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetUtxoSwapId() string {
	if x != nil {
		return x.UtxoSwapId
	}
	return ""
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetSpendTxSigningJob() *spark.SigningJob {
	if x != nil {
		return x.SpendTxSigningJob
	}
	return nil
}

type ClaimInstantStaticDepositUtxoSwapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SE co-signature over the SSP's spend transaction.
	SpendTxSigningResult *spark.SigningResult `protobuf:"bytes,1,opt,name=spend_tx_signing_result,json=spendTxSigningResult,proto3" json:"spend_tx_signing_result,omitempty"`
	// Secondary transfer, present iff the reservation carried a secondary credit.
	Transfer       *spark.Transfer                  `protobuf:"bytes,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	DepositAddress *spark.DepositAddressQueryResult `protobuf:"bytes,3,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) Reset() {
	*x = ClaimInstantStaticDepositUtxoSwapResponse{}
	mi := &file_spark_ssp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimInstantStaticDepositUtxoSwapResponse) ProtoMessage() {}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimInstantStaticDepositUtxoSwapResponse.ProtoReflect.Descriptor instead.
func (*ClaimInstantStaticDepositUtxoSwapResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) GetSpendTxSigningResult() *spark.SigningResult {
	if x != nil {
		return x.SpendTxSigningResult
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) GetDepositAddress() *spark.DepositAddressQueryResult {
	if x != nil {
		return x.DepositAddress
	}
	return nil
}

var File_spark_ssp_proto protoreflect.FileDescriptor

const file_spark_ssp_proto_rawDesc = "" +
	"\n" +
	"\x0fspark_ssp.proto\x12\tspark_ssp\x1a\vspark.proto\"\xee\x03\n" +
	"*ReserveInstantStaticDepositUtxoSwapRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12#\n" +
	"\rssp_signature\x18\x02 \x01(\fR\fsspSignature\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\fR\ruserSignature\x127\n" +
	"\btransfer\x18\x04 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\tR\x12destinationAddress\x12\x1d\n" +
	"\n" +
	"value_sats\x18\x06 \x01(\x03R\tvalueSats\x12,\n" +
	"\x12credit_amount_sats\x18\a \x01(\x03R\x10creditAmountSats\x12?\n" +
	"\x1csecondary_credit_amount_sats\x18\b \x01(\x03R\x19secondaryCreditAmountSats\x12E\n" +
	"\x1frequested_secondary_transfer_id\x18\n" +
	" \x01(\tR\x1crequestedSecondaryTransferIdJ\x04\b\t\x10\n" +
	"\"|\n" +
	"+ReserveInstantStaticDepositUtxoSwapResponse\x12+\n" +
	"\btransfer\x18\x01 \x01(\v2\x0f.spark.TransferR\btransfer\x12 \n" +
	"\futxo_swap_id\x18\x02 \x01(\tR\n" +
	"utxoSwapId\"\xfa\x01\n" +
	"(ClaimInstantStaticDepositUtxoSwapRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12 \n" +
	"\futxo_swap_id\x18\x02 \x01(\tR\n" +
	"utxoSwapId\x127\n" +
	"\btransfer\x18\x03 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12B\n" +
	"\x14spend_tx_signing_job\x18\x04 \x01(\v2\x11.spark.SigningJobR\x11spendTxSigningJob\"\xf0\x01\n" +
	")ClaimInstantStaticDepositUtxoSwapResponse\x12K\n" +
	"\x17spend_tx_signing_result\x18\x01 \x01(\v2\x14.spark.SigningResultR\x14spendTxSigningResult\x12+\n" +
	"\btransfer\x18\x02 \x01(\v2\x0f.spark.TransferR\btransfer\x12I\n" +
	"\x0fdeposit_address\x18\x03 \x01(\v2 .spark.DepositAddressQueryResultR\x0edepositAddress2\x9e\x05\n" +
	"\x0fSparkSspService\x12]\n" +
	"\x14prepare_tree_address\x12 .spark.PrepareTreeAddressRequest\x1a!.spark.PrepareTreeAddressResponse\"\x00\x12D\n" +
	"\vcreate_tree\x12\x18.spark.CreateTreeRequest\x1a\x19.spark.CreateTreeResponse\"\x00\x12W\n" +
	"\x14counter_leaf_swap_v3\x12\x1d.spark.CounterLeafSwapRequest\x1a\x1e.spark.CounterLeafSwapResponse\"\x00\x12W\n" +
	"\x12initiate_utxo_swap\x12\x1e.spark.InitiateUtxoSwapRequest\x1a\x1f.spark.InitiateUtxoSwapResponse\"\x00\x12\x9b\x01\n" +
	"(reserve_instant_static_deposit_utxo_swap\x125.spark_ssp.ReserveInstantStaticDepositUtxoSwapRequest\x1a6.spark_ssp.ReserveInstantStaticDepositUtxoSwapResponse\"\x00\x12\x95\x01\n" +
	"&claim_instant_static_deposit_utxo_swap\x123.spark_ssp.ClaimInstantStaticDepositUtxoSwapRequest\x1a4.spark_ssp.ClaimInstantStaticDepositUtxoSwapResponse\"\x00B0Z.github.com/lightsparkdev/spark/proto/spark_sspb\x06proto3"

var (
	file_spark_ssp_proto_rawDescOnce sync.Once
	file_spark_ssp_proto_rawDescData []byte
)

func file_spark_ssp_proto_rawDescGZIP() []byte {
	file_spark_ssp_proto_rawDescOnce.Do(func() {
		file_spark_ssp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_ssp_proto_rawDesc), len(file_spark_ssp_proto_rawDesc)))
	})
	return file_spark_ssp_proto_rawDescData
}

var file_spark_ssp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spark_ssp_proto_goTypes = []any{
	(*ReserveInstantStaticDepositUtxoSwapRequest)(nil),  // 0: spark_ssp.ReserveInstantStaticDepositUtxoSwapRequest
	(*ReserveInstantStaticDepositUtxoSwapResponse)(nil), // 1: spark_ssp.ReserveInstantStaticDepositUtxoSwapResponse
	(*ClaimInstantStaticDepositUtxoSwapRequest)(nil),    // 2: spark_ssp.ClaimInstantStaticDepositUtxoSwapRequest
	(*ClaimInstantStaticDepositUtxoSwapResponse)(nil),   // 3: spark_ssp.ClaimInstantStaticDepositUtxoSwapResponse
	(*spark.UTXO)(nil),                       // 4: spark.UTXO
	(*spark.StartTransferRequest)(nil),       // 5: spark.StartTransferRequest
	(*spark.Transfer)(nil),                   // 6: spark.Transfer
	(*spark.SigningJob)(nil),                 // 7: spark.SigningJob
	(*spark.SigningResult)(nil),              // 8: spark.SigningResult
	(*spark.DepositAddressQueryResult)(nil),  // 9: spark.DepositAddressQueryResult
	(*spark.PrepareTreeAddressRequest)(nil),  // 10: spark.PrepareTreeAddressRequest
	(*spark.CreateTreeRequest)(nil),          // 11: spark.CreateTreeRequest
	(*spark.CounterLeafSwapRequest)(nil),     // 12: spark.CounterLeafSwapRequest
	(*spark.InitiateUtxoSwapRequest)(nil),    // 13: spark.InitiateUtxoSwapRequest
	(*spark.PrepareTreeAddressResponse)(nil), // 14: spark.PrepareTreeAddressResponse
	(*spark.CreateTreeResponse)(nil),         // 15: spark.CreateTreeResponse
	(*spark.CounterLeafSwapResponse)(nil),    // 16: spark.CounterLeafSwapResponse
	(*spark.InitiateUtxoSwapResponse)(nil),   // 17: spark.InitiateUtxoSwapResponse
}
var file_spark_ssp_proto_depIdxs = []int32{
	4,  // 0: spark_ssp.ReserveInstantStaticDepositUtxoSwapRequest.on_chain_utxo:type_name -> spark.UTXO
	5,  // 1: spark_ssp.ReserveInstantStaticDepositUtxoSwapRequest.transfer:type_name -> spark.StartTransferRequest
	6,  // 2: spark_ssp.ReserveInstantStaticDepositUtxoSwapResponse.transfer:type_name -> spark.Transfer
	4,  // 3: spark_ssp.ClaimInstantStaticDepositUtxoSwapRequest.on_chain_utxo:type_name -> spark.UTXO
	5,  // 4: spark_ssp.ClaimInstantStaticDepositUtxoSwapRequest.transfer:type_name -> spark.StartTransferRequest
	7,  // 5: spark_ssp.ClaimInstantStaticDepositUtxoSwapRequest.spend_tx_signing_job:type_name -> spark.SigningJob
	8,  // 6: spark_ssp.ClaimInstantStaticDepositUtxoSwapResponse.spend_tx_signing_result:type_name -> spark.SigningResult
	6,  // 7: spark_ssp.ClaimInstantStaticDepositUtxoSwapResponse.transfer:type_name -> spark.Transfer
	9,  // 8: spark_ssp.ClaimInstantStaticDepositUtxoSwapResponse.deposit_address:type_name -> spark.DepositAddressQueryResult
	10, // 9: spark_ssp.SparkSspService.prepare_tree_address:input_type -> spark.PrepareTreeAddressRequest
	11, // 10: spark_ssp.SparkSspService.create_tree:input_type -> spark.CreateTreeRequest
	12, // 11: spark_ssp.SparkSspService.counter_leaf_swap_v3:input_type -> spark.CounterLeafSwapRequest
	13, // 12: spark_ssp.SparkSspService.initiate_utxo_swap:input_type -> spark.InitiateUtxoSwapRequest
	0,  // 13: spark_ssp.SparkSspService.reserve_instant_static_deposit_utxo_swap:input_type -> spark_ssp.ReserveInstantStaticDepositUtxoSwapRequest
	2,  // 14: spark_ssp.SparkSspService.claim_instant_static_deposit_utxo_swap:input_type -> spark_ssp.ClaimInstantStaticDepositUtxoSwapRequest
	14, // 15: spark_ssp.SparkSspService.prepare_tree_address:output_type -> spark.PrepareTreeAddressResponse
	15, // 16: spark_ssp.SparkSspService.create_tree:output_type -> spark.CreateTreeResponse
	16, // 17: spark_ssp.SparkSspService.counter_leaf_swap_v3:output_type -> spark.CounterLeafSwapResponse
	17, // 18: spark_ssp.SparkSspService.initiate_utxo_swap:output_type -> spark.InitiateUtxoSwapResponse
	1,  // 19: spark_ssp.SparkSspService.reserve_instant_static_deposit_utxo_swap:output_type -> spark_ssp.ReserveInstantStaticDepositUtxoSwapResponse
	3,  // 20: spark_ssp.SparkSspService.claim_instant_static_deposit_utxo_swap:output_type -> spark_ssp.ClaimInstantStaticDepositUtxoSwapResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_spark_ssp_proto_init() }
func file_spark_ssp_proto_init() {
	if File_spark_ssp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_ssp_proto_rawDesc), len(file_spark_ssp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spark_ssp_proto_goTypes,
		DependencyIndexes: file_spark_ssp_proto_depIdxs,
		MessageInfos:      file_spark_ssp_proto_msgTypes,
	}.Build()
	File_spark_ssp_proto = out.File
	file_spark_ssp_proto_goTypes = nil
	file_spark_ssp_proto_depIdxs = nil
}
