// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: spark_ssp.proto

package spark_ssp

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on
// ReserveInstantStaticDepositUtxoSwapRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReserveInstantStaticDepositUtxoSwapRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ReserveInstantStaticDepositUtxoSwapRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ReserveInstantStaticDepositUtxoSwapRequestMultiError, or nil if none found.
func (m *ReserveInstantStaticDepositUtxoSwapRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReserveInstantStaticDepositUtxoSwapRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOnChainUtxo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOnChainUtxo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReserveInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "OnChainUtxo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SspSignature

	// no validation rules for UserSignature

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReserveInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DestinationAddress

	// no validation rules for ValueSats

	// no validation rules for CreditAmountSats

	// no validation rules for SecondaryCreditAmountSats

	// no validation rules for RequestedSecondaryTransferId

	if len(errors) > 0 {
		return ReserveInstantStaticDepositUtxoSwapRequestMultiError(errors)
	}

	return nil
}

// ReserveInstantStaticDepositUtxoSwapRequestMultiError is an error wrapping
// multiple validation errors returned by
// ReserveInstantStaticDepositUtxoSwapRequest.ValidateAll() if the designated
// constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReserveInstantStaticDepositUtxoSwapRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReserveInstantStaticDepositUtxoSwapRequestMultiError) AllErrors() []error { return m }

// ReserveInstantStaticDepositUtxoSwapRequestValidationError is the validation
// error returned by ReserveInstantStaticDepositUtxoSwapRequest.Validate if
// the designated constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) ErrorName() string {
	return "ReserveInstantStaticDepositUtxoSwapRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReserveInstantStaticDepositUtxoSwapRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReserveInstantStaticDepositUtxoSwapRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReserveInstantStaticDepositUtxoSwapRequestValidationError{}

// Validate checks the field values on
// ReserveInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReserveInstantStaticDepositUtxoSwapResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ReserveInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ReserveInstantStaticDepositUtxoSwapResponseMultiError, or nil if none found.
func (m *ReserveInstantStaticDepositUtxoSwapResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReserveInstantStaticDepositUtxoSwapResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReserveInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UtxoSwapId

	if len(errors) > 0 {
		return ReserveInstantStaticDepositUtxoSwapResponseMultiError(errors)
	}

	return nil
}

// ReserveInstantStaticDepositUtxoSwapResponseMultiError is an error wrapping
// multiple validation errors returned by
// ReserveInstantStaticDepositUtxoSwapResponse.ValidateAll() if the designated
// constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReserveInstantStaticDepositUtxoSwapResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReserveInstantStaticDepositUtxoSwapResponseMultiError) AllErrors() []error { return m }

// ReserveInstantStaticDepositUtxoSwapResponseValidationError is the validation
// error returned by ReserveInstantStaticDepositUtxoSwapResponse.Validate if
// the designated constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) ErrorName() string {
	return "ReserveInstantStaticDepositUtxoSwapResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReserveInstantStaticDepositUtxoSwapResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReserveInstantStaticDepositUtxoSwapResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReserveInstantStaticDepositUtxoSwapResponseValidationError{}

// Validate checks the field values on ClaimInstantStaticDepositUtxoSwapRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ClaimInstantStaticDepositUtxoSwapRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ClaimInstantStaticDepositUtxoSwapRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ClaimInstantStaticDepositUtxoSwapRequestMultiError, or nil if none found.
func (m *ClaimInstantStaticDepositUtxoSwapRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ClaimInstantStaticDepositUtxoSwapRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOnChainUtxo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOnChainUtxo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "OnChainUtxo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UtxoSwapId

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSpendTxSigningJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "SpendTxSigningJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "SpendTxSigningJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpendTxSigningJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "SpendTxSigningJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ClaimInstantStaticDepositUtxoSwapRequestMultiError(errors)
	}

	return nil
}

// ClaimInstantStaticDepositUtxoSwapRequestMultiError is an error wrapping
// multiple validation errors returned by
// ClaimInstantStaticDepositUtxoSwapRequest.ValidateAll() if the designated
// constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClaimInstantStaticDepositUtxoSwapRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClaimInstantStaticDepositUtxoSwapRequestMultiError) AllErrors() []error { return m }

// ClaimInstantStaticDepositUtxoSwapRequestValidationError is the validation
// error returned by ClaimInstantStaticDepositUtxoSwapRequest.Validate if the
// designated constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) ErrorName() string {
	return "ClaimInstantStaticDepositUtxoSwapRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClaimInstantStaticDepositUtxoSwapRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClaimInstantStaticDepositUtxoSwapRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClaimInstantStaticDepositUtxoSwapRequestValidationError{}

// Validate checks the field values on
// ClaimInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ClaimInstantStaticDepositUtxoSwapResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ClaimInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ClaimInstantStaticDepositUtxoSwapResponseMultiError, or nil if none found.
func (m *ClaimInstantStaticDepositUtxoSwapResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ClaimInstantStaticDepositUtxoSwapResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSpendTxSigningResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "SpendTxSigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "SpendTxSigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpendTxSigningResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "SpendTxSigningResult",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDepositAddress()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "DepositAddress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "DepositAddress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDepositAddress()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "DepositAddress",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ClaimInstantStaticDepositUtxoSwapResponseMultiError(errors)
	}

	return nil
}

// ClaimInstantStaticDepositUtxoSwapResponseMultiError is an error wrapping
// multiple validation errors returned by
// ClaimInstantStaticDepositUtxoSwapResponse.ValidateAll() if the designated
// constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClaimInstantStaticDepositUtxoSwapResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClaimInstantStaticDepositUtxoSwapResponseMultiError) AllErrors() []error { return m }

// ClaimInstantStaticDepositUtxoSwapResponseValidationError is the validation
// error returned by ClaimInstantStaticDepositUtxoSwapResponse.Validate if the
// designated constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) ErrorName() string {
	return "ClaimInstantStaticDepositUtxoSwapResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClaimInstantStaticDepositUtxoSwapResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClaimInstantStaticDepositUtxoSwapResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClaimInstantStaticDepositUtxoSwapResponseValidationError{}
